"""Chaos harness: inject every fault in app/faults.py, one at a time, at the client boundary
where it would happen in production, run real events through the real pipeline, and check
the invariant that fault must not break. For each fault it prints what was injected, the
path taken (from the audit rows the run actually wrote), the fallback used and the final
state, and exits non-zero if any invariant fails.

    python scripts/chaos.py --fault llm_timeout
    python scripts/chaos.py --all [--write docs/failure_report.md]

Deterministic and offline by design: a throwaway SQLite file per fault (never ./recovery.db),
the in-memory Razorpay fixture, no LLM key, a fixed clock and injected sleeps. The report it
writes is reproducible byte for byte, so it is committed and regenerated by `make chaos`.
"""
import argparse
import json
import re
import shutil
import sys
import tempfile
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))  # importable from a clean clone, any cwd

from sqlalchemy import select  # noqa: E402

from app import config, db, executor, faults, ingest, llm, razorpay_client, scheduler  # noqa: E402
from app import classify as classify_mod  # noqa: E402
from app import policy as policy_mod  # noqa: E402
from app.classify import NO_RULE_MATCHED, RULES, classify_error  # noqa: E402
from app.clock import to_unix  # noqa: E402
from app.models import AuditEvent, Outcome, PaymentAttempt, RecoveryDecision, RecoveryJob, audit  # noqa: E402
from app.nudge_templates import format_rupees  # noqa: E402
from app import pipeline  # noqa: E402
from app.pipeline import PipelineDBError, process_attempt  # noqa: E402
from app.policy import human_delay  # noqa: E402
from app.razorpay_client import FaultingRazorpayClient, FixtureRazorpayClient, RazorpayError  # noqa: E402
from app.taxonomy import FailureClass  # noqa: E402
from scripts.seed import SEED_EVENTS, to_attempt  # noqa: E402

# A fixed clock: every timestamp below prints as an offset from T0, so two runs produce the same report.
T0 = datetime(2026, 9, 5, 12, 0, 0)
# A path SQLite cannot create: the first write fails at connect, which is what a dead database looks like.
BROKEN_DB_URL = "sqlite:////nonexistent/dir/recovery.db"
TRAIL_WIDTH = 190

INJECT = {
    "llm_timeout": "the LLM client raises TimeoutError on every call (FaultingLLM at the client boundary; "
                   "anthropic.APITimeoutError takes the same path)",
    "llm_bad_json": "the LLM returns truncated JSON on every call, the repair call included: "
                    "'{\"failure_class\": \"INSUFFICIENT_FUNDS\", \"confidence\": 0.8'",
    "llm_hallucinated_class": "the LLM returns well-formed JSON whose failure_class is CUSTOMER_MOVED_ABROAD "
                              "(not in the enum) at confidence 0.97, on every call",
    "razorpay_429": "the Payment Links API answers HTTP 429 to the first two create calls, then succeeds "
                    "(FaultingRazorpayClient wrapping the in-memory fixture)",
    "razorpay_5xx": "the Payment Links API answers HTTP 502 to every create call, for as long as the run lasts "
                    "(FaultingRazorpayClient wrapping the in-memory fixture)",
    "duplicate_event": "the same payment.failed event is delivered twice, one minute apart (webhooks are at-least-once); "
                       "no client is faulted",
    "unknown_error_code": "an error object no rule matches (issuer response code 96, 'system malfunction') "
                          "with no LLM configured (ANTHROPIC_API_KEY forced empty)",
    "db_unavailable": "the database is switched to an unopenable path after the event was ingested and before "
                      "the decision is written (sqlite:////nonexistent/dir/...); then two probes of the mirror "
                      "case, state lost after the request went out (a 'sent' write that never happened, and an "
                      "HTTP answer that never arrived)",
    "order_paid_elsewhere": "the customer pays the ORIGINAL order some other way (a checkout retry): a payment.captured "
                            "webhook arrives for the order after the recovery was decided but before it executed; then, "
                            "for a second order, after the recovery link was already sent; then with a Razorpay that "
                            "refuses the cancel; plus a probe of the pre-send order check against the fixture's memory",
}

INJECTED_AT = {
    "llm_timeout": "LLM client", "llm_bad_json": "LLM client", "llm_hallucinated_class": "LLM client",
    "razorpay_429": "Razorpay client", "razorpay_5xx": "Razorpay client",
    "duplicate_event": "event source (redelivery)", "unknown_error_code": "rules + LLM config",
    "db_unavailable": "database engine",
    "order_paid_elsewhere": "event source (payment.captured)",
}

INVARIANT = {
    "llm_timeout": "decision classified_by=fallback, action human_queue, zero links; nudge degrades to the template",
    "llm_bad_json": "exactly 2 model calls (one repair), human_queue, zero links",
    "llm_hallucinated_class": "class rejected (never coerced), human_queue, zero links",
    "razorpay_429": "link created exactly once, attempts_made == 3, status sent",
    "razorpay_5xx": "status failed, attempts_made == MAX_HTTP_ATTEMPTS, zero links; each failure reconciled by "
                    "reference_id before the next attempt is minted; follow-ups stop at max_attempts",
    "duplicate_event": "one job row, one link; second delivery skipped_duplicate with an audit row",
    "unknown_error_code": "UNKNOWN by rules, LLM unavailable, human_queue, zero links",
    "db_unavailable": "PipelineDBError raised, zero Razorpay calls; redelivery after recovery creates exactly one "
                      "link; a lost 'sent' write and a lost HTTP answer both resolve to the one existing link",
    "order_paid_elsewhere": "paid before execution: job no_action, outcome written, ZERO links, zero create calls; paid "
                            "after the link was sent: exactly one cancel call, link cancelled, job cancelled, outcome "
                            "written; cancel refused: job human_queue with the reason, never a silent live link",
}

WHY = {
    "llm_timeout": "A model that does not answer must neither stall the event nor be guessed around: parking it for a "
                   "person costs one review, while guessing a class could retry a risk-flagged card or burn an issuer "
                   "attempt; the nudge falls to a template because message generation must never block a recovery.",
    "llm_bad_json": "Malformed output earns exactly one repair call, because a second chance is cheap but an unbounded "
                    "repair loop is latency and cost with no guarantee, and after that a human review is the only "
                    "honest answer.",
    "llm_hallucinated_class": "The class enum is closed: an invented class has no row in the policy table, so mapping it "
                              "to the nearest real class would be a guess dressed up as a decision; rejection plus a "
                              "human review is the only outcome that does not move money on a hallucination.",
    "razorpay_429": "A rate limit means later, not no: bounded exponential backoff respects it, and because the job row "
                    "and its reference_id already exist, every retry is the same link, never a second one.",
    "razorpay_5xx": "When the gateway is down the right result is a failed job with evidence (three attempts, the error "
                    "text) and a follow-up from the policy table, not an infinite loop and not a silent drop; a 5xx "
                    "does not prove the request was dropped, so each failed attempt is reconciled against Razorpay by "
                    "reference_id before the next one is minted under a new key, and the stop rule caps how long an "
                    "outage can keep the agent knocking on the issuer's door.",
    "duplicate_event": "Webhooks are at-least-once, so double delivery is normal and its only acceptable cost is one "
                       "extra audit row: the sha256(payment_id:retry_seq) key is UNIQUE in the database and inserted "
                       "before any outbound call, so a redelivery cannot mint a second link, let alone a second charge.",
    "unknown_error_code": "An error object no rule matches, with no model to ask, is precisely the case an automated "
                          "system must not guess: the customer keeps their money, a person decides, and if the code "
                          "recurs the rules table gains a row rather than the agent gaining a habit.",
    "db_unavailable": "If the job row cannot be written, nothing may go out: a link that exists without a record is "
                      "unreconcilable, whereas an unacknowledged event is simply redelivered, meets the same idempotency "
                      "key, and is handled exactly once. When state is lost after the request went out, the "
                      "reference_id is the record: the link is looked up and recorded, never re-created.",
    "order_paid_elsewhere": "A recovery link is a second way to pay the same order, so the moment the order is paid the "
                            "link is a double-payment risk and every pending attempt is noise: the guard runs before any "
                            "outbound call (and again at execution, whatever path led there), a live link is cancelled at "
                            "Razorpay rather than left to expire, and if the cancel itself fails the payment is parked for "
                            "a person because a live link nobody is watching is exactly the failure this agent exists to "
                            "prevent.",
}

# llm_* faults: which UNKNOWN seed event, how many model calls each call site must make, and the nudge fallback name
UNMAPPED_EVENT_INDEX = {"llm_timeout": 1, "llm_bad_json": 2, "llm_hallucinated_class": 0}
CLASSIFY_CALLS = {"llm_timeout": 1, "llm_bad_json": 2, "llm_hallucinated_class": 2}
NUDGE_CALLS = {"llm_timeout": 1, "llm_bad_json": 2, "llm_hallucinated_class": 2}
CALLS_NOTE = {
    "llm_timeout": "an exception is not an answer that can be repaired, so no repair call",
    "llm_bad_json": "one attempt plus one repair, then stop",
    "llm_hallucinated_class": "one attempt plus one repair, then stop",
}
# the hallucinated classification JSON fails the nudge schema, so that call site reports it as bad JSON
NUDGE_FALLBACK = {"llm_timeout": "llm_timeout->template", "llm_bad_json": "llm_bad_json->template",
                  "llm_hallucinated_class": "llm_bad_json->template"}

# Not in the seed on purpose: an issuer response code the rules were never taught. ISO 8583 code 96 is
# "system malfunction", which a person might call ISSUER_DOWN; the point is that the agent does not.
UNKNOWN_CODE_EVENT = {
    "razorpay_payment_id": "pay_ChaosRc96Unmap", "order_id": "order_ChaosRc96Unmap", "merchant_id": "merchant_chaos",
    "customer_name": "Test Customer", "customer_contact": "+919999900000", "customer_email": None,
    "amount_paise": 129900, "currency": "INR", "method": "card", "has_token": False, "failed_minutes_ago": 3,
    "error": {"code": "BAD_REQUEST_ERROR", "source": "bank", "step": "payment_authorization", "reason": "payment_failed",
              "description": "Issuer returned response code 96 (system malfunction); transaction not approved.",
              "metadata": {"issuer_rc": "96"}},
    "expected_class": FailureClass.UNKNOWN,
}


# ---- result model ------------------------------------------------------------------------------

@dataclass
class Trace:
    label: str
    trail: list[tuple[str, str]]  # (stage, message) in audit order

    def path(self) -> str:
        steps: list[list] = []
        for stage, _ in self.trail:
            if steps and steps[-1][0] == stage:
                steps[-1][1] += 1
            else:
                steps.append([stage, 1])
        return " -> ".join(f"{s} x{n}" if n > 1 else s for s, n in steps)


@dataclass
class Result:
    fault: str
    inject: str = ""
    events: list[str] = field(default_factory=list)
    traces: list[Trace] = field(default_factory=list)
    fallback: str = ""
    final_state: str = ""
    summary: str = ""
    checks: list[tuple[bool, str]] = field(default_factory=list)
    error: str | None = None

    def check(self, ok, what: str) -> bool:
        self.checks.append((bool(ok), what))
        return bool(ok)

    @property
    def passed(self) -> bool:
        return self.error is None and bool(self.checks) and all(ok for ok, _ in self.checks)

    @property
    def verdict(self) -> str:
        return "PASS" if self.passed else "FAIL"


# ---- helpers -------------------------------------------------------------------------------------

def _event(cls: FailureClass, index: int = 0) -> dict:
    return [e for e in SEED_EVENTS if e["expected_class"] is cls][index]


def _describe_event(ev: dict) -> str:
    err = ev["error"]
    desc = err["description"] if len(err["description"]) <= 90 else err["description"][:87] + "..."
    token = " (saved token)" if ev["has_token"] else ""
    return (f"{ev['razorpay_payment_id']} {ev['method']} {format_rupees(ev['amount_paise'])}{token}: "
            f"{err['code']} / {err['source']} / {err['step']} / {err['reason']}: \"{desc}\"")


def _find(session, payment_id: str) -> PaymentAttempt | None:
    return session.execute(select(PaymentAttempt).where(PaymentAttempt.razorpay_payment_id == payment_id)).scalars().first()


def _deliver(session, ev: dict, *, now: datetime, rz, lm, sleeps: list, execute_now: bool = True) -> dict:
    """What a webhook receiver does: look the payment up by id (a redelivery finds the existing row),
    otherwise hand the raw event to the pipeline, which ingests it as part of the acknowledgement."""
    row = _find(session, ev["razorpay_payment_id"]) or to_attempt(ev, now=now)
    return process_attempt(session, row, execute_now=execute_now, now=now, rz_client=rz, llm_client=lm,
                           sleep=sleeps.append)


def _ingest(session, ev: dict, now: datetime) -> PaymentAttempt:
    """Store the event without deciding anything (what seed.py does), so a later delivery finds it."""
    row = to_attempt(ev, now=now)
    session.add(row)
    session.flush()
    audit(session, row.id, "ingest", "failed payment event received",
          {"razorpay_payment_id": row.razorpay_payment_id, "method": row.method, "amount_paise": row.amount_paise,
           "error": ev["error"], "has_token": row.has_token})
    session.commit()
    return row


def _audit_rows(session, attempt_id: int) -> list[AuditEvent]:
    return list(session.execute(select(AuditEvent).where(AuditEvent.attempt_id == attempt_id)
                                .order_by(AuditEvent.id)).scalars().all())


def _trail(session, attempt_id: int) -> list[tuple[str, str]]:
    return [(r.stage, r.message) for r in _audit_rows(session, attempt_id)]


def _decisions(session, attempt_id: int) -> list[RecoveryDecision]:
    return list(session.execute(select(RecoveryDecision).where(RecoveryDecision.attempt_id == attempt_id)
                                .order_by(RecoveryDecision.id)).scalars().all())


def _jobs(session, attempt_id: int) -> list[RecoveryJob]:
    return list(session.execute(select(RecoveryJob).where(RecoveryJob.attempt_id == attempt_id)
                                .order_by(RecoveryJob.id)).scalars().all())


def _outcome(session, attempt_id: int) -> Outcome | None:
    return session.execute(select(Outcome).where(Outcome.attempt_id == attempt_id).order_by(Outcome.id)).scalars().first()


def _creates(fx: FixtureRazorpayClient) -> int:
    return sum(1 for name, _ in fx.calls if name == "create_payment_link")


_ISO = re.compile(r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?")


def _offset(seconds: int) -> str:
    """2885 minutes reads badly; 48h5m does not."""
    h, rest = divmod(seconds, 3600)
    m, s = divmod(rest, 60)
    return "".join(f"{v}{u}" for v, u in ((h, "h"), (m, "m"), (s, "s")) if v) or "0s"


def _relative(text: str) -> str:
    """Absolute timestamps in audit messages become offsets from T0 ("T0+45m")."""
    def repl(m):
        delta = int((datetime.fromisoformat(m.group(0)) - T0).total_seconds())
        if delta == 0:
            return "T0"
        return f"T0{'+' if delta > 0 else '-'}{_offset(abs(delta))}"
    return _ISO.sub(repl, text)


def _clip(text: str, width: int = TRAIL_WIDTH) -> str:
    return text if len(text) <= width else text[:width - 3] + "..."


# ---- scenarios -----------------------------------------------------------------------------------

def scenario_llm(r: Result, session, sleeps: list) -> None:
    """The two call sites, both degraded: classification of an unmapped event (-> human queue) and
    the customer nudge for a rules-classified link event (-> template). The link is still created."""
    fault = r.fault
    lm = llm.get_client()
    r.check(isinstance(lm, llm.FaultingLLM) and lm.fault == fault,
            f"llm.get_client() resolves FaultingLLM({fault}): faults beat API keys, nothing reaches the network")
    rz = razorpay_client.get_client()
    fx = razorpay_client.fixture()

    ev = _event(FailureClass.UNKNOWN, UNMAPPED_EVENT_INDEX[fault])
    r.events.append("unmapped event: " + _describe_event(ev))
    s = _deliver(session, ev, now=T0, rz=rz, lm=lm, sleeps=sleeps)
    classify_calls = len(lm.calls)
    trail = _trail(session, s["attempt_id"])
    r.traces.append(Trace("unmapped event", trail))
    d = _decisions(session, s["attempt_id"])[-1]
    job = session.get(RecoveryJob, s["job_id"])
    o = _outcome(session, s["attempt_id"])

    r.check(any(st == "classify" and m.startswith(f"UNKNOWN (rules): {NO_RULE_MATCHED}") for st, m in trail),
            "rules classified the event UNKNOWN (no rule matched) before any model was asked")
    r.check(classify_calls == CLASSIFY_CALLS[fault],
            f"exactly {CLASSIFY_CALLS[fault]} model call(s) for classification ({CALLS_NOTE[fault]})")
    r.check(d.classified_by == "fallback" and d.fallback_taken == f"{fault}->human_queue",
            f"decision classified_by=fallback, fallback_taken={fault}->human_queue")
    r.check(d.failure_class == "UNKNOWN" and d.confidence == 0.0,
            "the rejected answer was not coerced into a class: UNKNOWN at confidence 0.0, which never clears the 0.7 gate")
    r.check(d.action == "human_queue" and job.status == "human_queue", "action human_queue; the job row is parked, not pending")
    r.check(d.llm_used is True and d.llm_model == f"faulting-{fault}",
            "the decision row records that a model was consulted, and which one, even though it failed")
    r.check(job.razorpay_link_id is None and fx.links() == [] and fx.calls == [], "zero payment links, zero Razorpay calls")
    r.check(o is not None and o.recovered is False and (o.note or "").startswith("human_queue"),
            "outcome recorded at decision time: not recovered, human_queue")

    ev2 = _event(FailureClass.HARD_DECLINE, 0)
    r.events.append("nudge probe (rules-classified, link + message): " + _describe_event(ev2))
    s2 = _deliver(session, ev2, now=T0, rz=rz, lm=lm, sleeps=sleeps)
    nudge_calls = len(lm.calls) - classify_calls
    trail2 = _trail(session, s2["attempt_id"])
    r.traces.append(Trace("nudge probe", trail2))
    job2 = session.get(RecoveryJob, s2["job_id"])
    nudge_msgs = [m for st, m in trail2 if st == "nudge"]
    expected = NUDGE_FALLBACK[fault]
    r.check(s2["job_status"] == "sent" and len(fx.links()) == 1,
            "nudge probe: the link was created before the message was drafted; message generation never blocks a recovery")
    r.check(job2.nudge_source == "template" and bool(nudge_msgs) and f"(fallback: {expected})" in nudge_msgs[0],
            f"nudge probe: message drafted from the per-class template, audit row names the fallback {expected}")
    r.check(nudge_calls == NUDGE_CALLS[fault], f"nudge probe: exactly {NUDGE_CALLS[fault]} model call(s) for the message")
    r.check((job2.razorpay_link_url or "") in (job2.nudge_body or "") and format_rupees(ev2["amount_paise"]) in (job2.nudge_body or ""),
            "nudge probe: the template carries the real short_url and the exact amount")

    r.fallback = f"classification: {fault}->human_queue (a person decides); nudge: {expected} (per-class template)"
    r.final_state = (f"unmapped event: job#{job.id} human_queue, links=0, outcome=not recovered (human_queue); "
                     f"nudge probe: job#{job2.id} sent {job2.razorpay_link_url}, nudge=template [{expected}], links=1 (its own)")
    r.summary = "human_queue, 0 links; nudge from template"


def scenario_razorpay_429(r: Result, session, sleeps: list) -> None:
    rz = razorpay_client.get_client()
    fx = razorpay_client.fixture()
    r.check(isinstance(rz, FaultingRazorpayClient) and rz.fault == "razorpay_429" and rz.inner is fx,
            "razorpay_client.get_client() resolves the faulting wrapper around the in-memory fixture")
    lm = llm.get_client()
    ev = _event(FailureClass.HARD_DECLINE, 1)  # delay 0: executes on its own, no execute_now needed
    r.events.append(_describe_event(ev))
    s = _deliver(session, ev, now=T0, rz=rz, lm=lm, sleeps=sleeps, execute_now=False)
    rows = _audit_rows(session, s["attempt_id"])
    r.traces.append(Trace("event", [(x.stage, x.message) for x in rows]))
    job = session.get(RecoveryJob, s["job_id"])
    backoffs = [x for x in rows if x.stage == "execute" and "backing off" in x.message]
    sent = [x for x in rows if x.stage == "execute" and x.message.startswith("sent: payment link")]
    sent_client = json.loads(sent[0].data_json).get("client") if sent and sent[0].data_json else None

    r.check(job.status == "sent" and job.razorpay_link_id is not None, "job status sent with a link id")
    r.check(job.attempts_made == 3 and rz.create_calls == 3,
            "attempts_made == 3 (two 429s, then success); the client saw exactly 3 create calls")
    r.check(len(fx.links()) == 1 and fx.links()[0]["id"] == job.razorpay_link_id,
            "exactly one payment link exists at the fixture, and it is the job's")
    r.check(sleeps == [0.5, 1.0], f"exponential backoff 0.5s then 1.0s, no sleep after the final attempt (recorded, not waited): {sleeps}")
    r.check(len(backoffs) == 2, "two 'backing off' audit rows carry the HTTP status and the wait")
    r.check(sent_client == "fault:razorpay_429", "the 'sent' audit row names the client that answered (fault:razorpay_429)")
    r.check(fx.links()[0]["reference_id"] == job.idempotency_key[:40],
            "the link's reference_id is the idempotency key (first 40 chars): a retry after a crash would collide there too")
    r.check(job.nudge_source == "template" and (job.razorpay_link_url or "") in (job.nudge_body or ""),
            "nudge drafted after the link exists, with the real short_url")

    # A max_attempts=1 class throttled on every attempt: the recovery never reached the customer, so
    # it must be parked for a person, not closed "no_action: max attempts reached" (a rate limit is a
    # delivery failure, not an exhausted recovery).
    class _Always429:
        name = "always-429"

        def create_payment_link(self, payload):
            raise RazorpayError(429, "BAD_REQUEST_ERROR", "Too many requests")

        def fetch_payment_link(self, link_id):
            raise AssertionError("never fetched")

        def list_payment_links(self, *, reference_id):
            return []

    ev2 = _event(FailureClass.HARD_DECLINE, 2)
    r.events.append("delivery-exhausted probe (max_attempts=1, throttled on every attempt): " + _describe_event(ev2))
    s2 = _deliver(session, ev2, now=T0, rz=_Always429(), lm=lm, sleeps=sleeps, execute_now=True)
    job2 = session.get(RecoveryJob, s2["job_id"])
    follow = session.get(RecoveryJob, s2["followup_job_id"]) if s2["followup_job_id"] else None
    o2 = _outcome(session, s2["attempt_id"])
    r.traces.append(Trace("delivery-exhausted probe (max_attempts=1 throttled on every send)",
                          _trail(session, s2["attempt_id"])))
    r.check(job2.status == "failed" and executor.failure_kind(job2) == executor.RATE_LIMITED and job2.attempts_made == 3,
            "delivery-exhausted probe: the only send was rate-limited on all 3 attempts (kind rate_limited), no link")
    r.check(follow is not None and follow.status == "human_queue",
            "delivery-exhausted probe: parked human_queue, not closed 'no_action: max attempts reached'")
    r.check(o2 is not None and not o2.recovered and (o2.note or "").startswith("human_queue") and "throttled" in (o2.note or ""),
            "delivery-exhausted probe: the outcome records the throttle, so a rate limit is not mistaken for recovery exhausted")

    r.fallback = ("bounded exponential backoff on 429 (0.5s, 1.0s), then success on attempt 3 of 3; a max_attempts=1 "
                  "class throttled on every attempt is parked for a person, not closed as recovery exhausted")
    r.final_state = (f"job#{job.id} sent {job.razorpay_link_url}, attempts_made=3, links=1, outcome=open; "
                     f"delivery-exhausted probe: job#{job2.id} failed (rate_limited), follow-up job#{follow.id} human_queue")
    r.summary = "sent after 2 backoffs, 1 link"


def scenario_razorpay_5xx(r: Result, session, sleeps: list) -> None:
    rz = razorpay_client.get_client()
    fx = razorpay_client.fixture()
    r.check(isinstance(rz, FaultingRazorpayClient) and rz.fault == "razorpay_5xx" and rz.inner is fx,
            "razorpay_client.get_client() resolves the faulting wrapper around the in-memory fixture")
    lm = llm.get_client()
    ev = _event(FailureClass.ISSUER_DOWN, 1)  # netbanking, no token: link at 15m, backoff x3, max 3 attempts
    r.events.append(_describe_event(ev) + "  [execute_now: the harness does not wait 15 minutes]")
    s = _deliver(session, ev, now=T0, rz=rz, lm=lm, sleeps=sleeps, execute_now=True)
    job = session.get(RecoveryJob, s["job_id"])

    r.check(job.status == "failed" and "502" in (job.last_error or ""),
            "job status failed; last_error carries the HTTP 502 the gateway returned")
    r.check(job.attempts_made == executor.MAX_HTTP_ATTEMPTS and rz.create_calls == 3,
            f"attempts_made == MAX_HTTP_ATTEMPTS ({executor.MAX_HTTP_ATTEMPTS}); the client saw exactly 3 create calls")
    r.check(job.razorpay_link_id is None and fx.links() == [], "zero payment links")
    r.check(sleeps == [0.5, 1.0], f"backoff 0.5s then 1.0s between attempts, then stop (recorded, not waited): {sleeps}")
    r.check(job.nudge_body is None, "no customer message drafted: there is no link to send")
    r.check(s["followup_status"] == "pending" and s["followup_scheduled_at"] == T0 + timedelta(seconds=2700)
            and session.get(RecoveryJob, s["followup_job_id"]).retry_seq == 2,
            "follow-up seq 2 scheduled at T0+45m (15m x3 from the policy table), under its own idempotency key")

    # the outage persists: the scheduler walks the backoff chain to the stop rule
    t = T0
    for delay in (2700, 8100):
        t += timedelta(seconds=delay)
        scheduler.run_due(session, now=t, rz_client=rz, llm_client=lm, sleep=sleeps.append)
    rows = _audit_rows(session, s["attempt_id"])
    r.traces.append(Trace("event, then the scheduler while the outage persists", [(x.stage, x.message) for x in rows]))
    jobs = _jobs(session, s["attempt_id"])
    o = _outcome(session, s["attempt_id"])
    r.check([j.retry_seq for j in jobs] == [1, 2, 3, 4] and [j.status for j in jobs] == ["failed"] * 3 + ["no_action"],
            "backoff chain: seq 1, 2, 3 failed (T0, T0+45m, T0+3h), seq 4 no_action by the stop rule (max 3 attempts)")
    r.check(len({j.idempotency_key for j in jobs}) == 4 and all(j.attempts_made == 3 for j in jobs[:3]),
            "each attempt has its own idempotency key and exactly 3 HTTP attempts")
    r.check(rz.create_calls == 9 and fx.links() == [], "9 HTTP attempts in total, still zero links")
    r.check(any(x.stage == "policy" and "stop rule: max attempts reached" in x.message for x in rows),
            "the stop rule is written to the trail in the policy's own words")
    reconciled = [x for x in rows if x.stage == "reconcile"]
    r.check(len(reconciled) == 3 and all("no link at Razorpay" in x.message for x in reconciled)
            and all(executor.failure_kind(j) == executor.SERVER_ERROR for j in jobs[:3]),
            "a 5xx is ambiguous (the request may have been processed), so each failed attempt was reconciled by "
            "reference_id lookup before the next key was minted: no link found each time, follow-up safe")
    r.check(o is not None and o.recovered is False and (o.note or "").startswith("no_action"),
            "outcome recorded: not recovered (no_action), so the payment is visibly closed, not silently dropped")

    r.fallback = ("bounded retries per attempt (3, with backoff), job marked failed with the error kept; reconcile by "
                  "reference_id (no link) before each follow-up; policy follow-ups at x3 backoff until max_attempts, "
                  "then no_action")
    r.final_state = ("jobs seq1 failed (3 attempts) -> seq2 failed (3) -> seq3 failed (3) -> seq4 no_action (stop rule); "
                     "links=0; HTTP attempts=9; outcome=not recovered (no_action)")
    r.summary = "failed x3, stop rule, 0 links"


def scenario_duplicate_event(r: Result, session, sleeps: list) -> None:
    rz = razorpay_client.get_client()
    fx = razorpay_client.fixture()
    r.check(isinstance(rz, FixtureRazorpayClient), "no client fault: the fixture answers every create")
    lm = llm.get_client()
    ev = _event(FailureClass.AUTH_ABANDONED, 0)
    r.events.append(_describe_event(ev) + "  [delivered at T0 and again at T0+1m; execute_now]")
    first = _deliver(session, ev, now=T0, rz=rz, lm=lm, sleeps=sleeps)
    second = _deliver(session, ev, now=T0 + timedelta(minutes=1), rz=rz, lm=lm, sleeps=sleeps)
    pid = ev["razorpay_payment_id"]
    key = executor.idempotency_key(pid, 1)
    rows = _audit_rows(session, first["attempt_id"])
    jobs = _jobs(session, first["attempt_id"])
    decisions = _decisions(session, first["attempt_id"])

    r.check(first["job_status"] == "sent" and bool(first["link_url"]), "delivery 1: job sent, link created")
    r.check(second["duplicate"] is True and second["job_status"] == "skipped_duplicate"
            and second["job_id"] == first["job_id"] and second["existing_job_status"] == "sent",
            "delivery 2: skipped_duplicate, pointing at the existing sent job")
    r.check(len(jobs) == 1 and jobs[0].idempotency_key == key,
            f"one job row, under sha256('{pid}:1') = {key[:16]}... (UNIQUE in recovery_jobs)")
    r.check(len(fx.links()) == 1 and _creates(fx) == 1, "one payment link, one create call")
    r.check(sum(1 for x in rows if "skipped_duplicate" in x.message) == 1, "exactly one skipped_duplicate audit row")
    r.check(not any("already executed" in x.message for x in rows),
            "the duplicate never reached execute: refused at schedule, before any outbound call")
    r.check(len(decisions) == 2 and decisions[0].failure_class == decisions[1].failure_class == "AUTH_ABANDONED"
            and decisions[0].action == decisions[1].action,
            "both deliveries are in the trail with identical (deterministic) decisions")
    r.check(fx.links()[0]["reference_id"] == key[:40],
            "the link's reference_id at Razorpay is the same key: the guard survives even a lost job row")

    # belt and braces: the second guard, on the job itself
    creates_before = _creates(fx)
    job = executor.execute_job(session, jobs[0], client=rz, now=T0 + timedelta(minutes=2), sleep=sleeps.append)
    rows = _audit_rows(session, first["attempt_id"])
    r.traces.append(Trace("both deliveries, then execute_job forced on the sent job", [(x.stage, x.message) for x in rows]))
    r.check(job.status == "sent" and _creates(fx) == creates_before and any("already executed" in x.message for x in rows),
            "forcing execute_job on the sent job: refused ('already executed'), zero calls")

    r.fallback = "INSERT under the UNIQUE idempotency key fails -> skipped_duplicate (audited), existing job untouched"
    r.final_state = (f"1 job row (job#{jobs[0].id}, key {key[:16]}...), 1 link {first['link_url']}, "
                     f"delivery 2 = skipped_duplicate (existing job sent); 2 decisions in the trail")
    r.summary = "1 job, 1 link, 2nd skipped"


def scenario_unknown_error_code(r: Result, session, sleeps: list) -> None:
    # A key IS configured here: the point of this fault is that it forces the LLM off anyway (an error
    # object no rule matches AND no model to ask), so the check must not pass just because no key is set.
    config.ANTHROPIC_API_KEY = "sk-ant-chaos-dummy"
    lm = llm.get_client()
    r.check(faults.is_active("unknown_error_code") and lm is None,
            "a key is configured, yet the unknown_error_code fault forces llm.get_client() to None")
    faults.deactivate("unknown_error_code")
    would_be = llm.get_client()
    faults.activate("unknown_error_code")
    r.check(isinstance(would_be, llm.AnthropicLLM),
            "the check is not vacuous: with the fault cleared and the same key, get_client() returns AnthropicLLM")
    rz = razorpay_client.get_client()
    fx = razorpay_client.fixture()
    ev = UNKNOWN_CODE_EVENT
    err = ev["error"]
    r.events.append(_describe_event(ev) + "  [not a seed event: crafted for this fault]")
    c = classify_error(err["code"], err["source"], err["step"], err["reason"], err["description"])
    r.check(c.failure_class is FailureClass.UNKNOWN and c.reason == NO_RULE_MATCHED and c.source == "rules",
            f"rules: none of the {len(RULES)} ordered rules match -> UNKNOWN ('{NO_RULE_MATCHED}'), never a nearest guess")
    s = _deliver(session, ev, now=T0, rz=rz, lm=lm, sleeps=sleeps)
    trail = _trail(session, s["attempt_id"])
    r.traces.append(Trace("event", trail))
    d = _decisions(session, s["attempt_id"])[-1]
    job = session.get(RecoveryJob, s["job_id"])
    o = _outcome(session, s["attempt_id"])

    r.check(d.classified_by == "fallback" and d.fallback_taken == "llm_unavailable->human_queue",
            "decision classified_by=fallback, fallback_taken=llm_unavailable->human_queue")
    r.check(d.llm_used is False and d.llm_model is None and d.llm_latency_ms is None,
            "no model was consulted: nothing to bill, nothing to wait for")
    r.check(d.action == "human_queue" and job.status == "human_queue", "action human_queue; the job row is parked")
    r.check(fx.calls == [] and fx.links() == [], "zero Razorpay calls, zero links")
    r.check(o is not None and o.recovered is False and (o.note or "").startswith("human_queue"),
            "outcome recorded: not recovered, human_queue")

    r.fallback = "rules -> UNKNOWN; llm_unavailable->human_queue (a person decides)"
    r.final_state = f"job#{job.id} human_queue, links=0, Razorpay calls=0, model calls=0, outcome=not recovered (human_queue)"
    r.summary = "human_queue, 0 links"


class _LostResponseClient:
    """The request lands (the fixture creates the link) but no HTTP answer ever comes back, on
    every attempt: the classic lost-response timeout that a naive retry turns into two links."""
    name = "lost-response"

    def __init__(self, inner: FixtureRazorpayClient):
        self.inner = inner

    def create_payment_link(self, payload: dict) -> dict:
        try:
            self.inner.create_payment_link(payload)
        except RazorpayError as exc:  # a retry of the same reference_id also lands and also gets no answer
            if "already exists" not in exc.description:
                raise
        raise RazorpayError(0, "NETWORK", "TimeoutError: the request was sent; the response never arrived")

    def fetch_payment_link(self, link_id: str) -> dict:
        return self.inner.fetch_payment_link(link_id)

    def list_payment_links(self, *, reference_id: str) -> list[dict]:
        return self.inner.list_payment_links(reference_id=reference_id)


def _probe_crash_after_send(r: Result, s3, fx: FixtureRazorpayClient, rz, lm, sleeps: list) -> RecoveryJob:
    """The request reached Razorpay, then the process died before writing status=sent."""
    ev2 = _event(FailureClass.ISSUER_DOWN, 1)
    r.events.append("crash-after-send probe: " + _describe_event(ev2))
    links_before = len(fx.links())
    s4 = _deliver(s3, ev2, now=T0 + timedelta(minutes=5), rz=rz, lm=lm, sleeps=sleeps, execute_now=False)
    job = s3.get(RecoveryJob, s4["job_id"])
    a2 = s3.get(PaymentAttempt, s4["attempt_id"])
    r.check(job.status == "pending", "crash probe: the pending job row is committed with its key before anything goes out")
    created = fx.create_payment_link(executor.build_payment_link_payload(a2, job, "ISSUER_DOWN", now=T0 + timedelta(minutes=5)))
    job.attempts_made = 1  # what the row looks like after such a crash: the counter is committed before the call
    s3.commit()
    job = executor.execute_job(s3, job, client=rz, now=T0 + timedelta(minutes=20), sleep=sleeps.append)
    r.traces.append(Trace("crash-after-send probe (link created, 'sent' never written, pending job re-run)",
                          _trail(s3, a2.id)))
    r.check(job.status == "sent" and job.razorpay_link_id == created["id"] and job.razorpay_link_url == created["short_url"]
            and "already exists" in (job.last_error or ""),
            "re-running the pending job: Razorpay rejects the duplicate reference_id -> the existing link is looked up "
            "by that reference_id and recorded on the job (id and short_url), nothing re-created")
    r.check(len(fx.links()) == links_before + 1 and len(_jobs(s3, a2.id)) == 1,
            "one link and one job for this payment; the repeat for the same reference_id was rejected, not fulfilled")
    r.check(created["id"] in [j.razorpay_link_id for j in pipeline.open_link_jobs(s3)],
            "the recovered link is visible to poll, so a customer payment on it will be recorded")
    return job


def _probe_lost_response(r: Result, s3, fx: FixtureRazorpayClient, lm, sleeps: list) -> RecoveryJob:
    """The request reached Razorpay on every attempt, but no answer ever came back."""
    ev3 = _event(FailureClass.AUTH_ABANDONED, 2)
    r.events.append("lost-response probe: " + _describe_event(ev3) + "  [execute_now]")
    links_before = len(fx.links())
    lost = _LostResponseClient(fx)
    s5 = _deliver(s3, ev3, now=T0 + timedelta(minutes=5), rz=lost, lm=lm, sleeps=sleeps, execute_now=True)
    job = s3.get(RecoveryJob, s5["job_id"])
    rows = _audit_rows(s3, s5["attempt_id"])
    r.traces.append(Trace("lost-response probe (every attempt lands, no answer arrives, then reconcile)",
                          [(x.stage, x.message) for x in rows]))
    reconciled = [x for x in rows if x.stage == "reconcile"]
    r.check(job.attempts_made == executor.MAX_HTTP_ATTEMPTS and any("transport" in x.message for x in rows if x.stage == "execute"),
            "lost-response probe: three attempts under one reference_id, each a transport failure (kind transport)")
    r.check(len(reconciled) == 1 and "had landed" in reconciled[0].message,
            "lost-response probe: the failure is ambiguous, so the job was reconciled by reference_id before any "
            "follow-up: the link was found")
    r.check(job.status == "sent" and job.razorpay_link_id is not None and job.razorpay_link_url in (job.nudge_body or ""),
            "lost-response probe: job marked sent with the recovered link, nudge drafted with its short_url")
    r.check(len(fx.links()) == links_before + 1 and len(_jobs(s3, s5["attempt_id"])) == 1 and s5["followup_job_id"] is None,
            "lost-response probe: exactly one link and one job; no follow-up minted under a second key")
    return job


def scenario_db_unavailable(r: Result, session, sleeps: list) -> None:
    """Four steps: the write refused before anything went out; the redelivery once the database is
    back; and two probes of the mirror case, state lost after the request went out (a 'sent' write
    that never happened, and an HTTP answer that never arrived)."""
    good_url = db.url()
    rz = razorpay_client.get_client()
    fx = razorpay_client.fixture()
    lm = llm.get_client()
    ev = _event(FailureClass.INSUFFICIENT_FUNDS, 0)
    r.events.append(_describe_event(ev))

    attempt = _ingest(session, ev, T0)  # the event exists durably; the outage starts after this
    attempt_id = attempt.id
    session.close()

    db.configure(BROKEN_DB_URL)
    broken = db.session()
    error = None
    try:
        process_attempt(broken, attempt, execute_now=True, now=T0, rz_client=rz, llm_client=lm, sleep=sleeps.append)
    except PipelineDBError as exc:
        error = str(exc)
    finally:
        broken.close()
        db.configure(good_url)
    cls = classify_mod.classify(attempt)
    pol = policy_mod.decide(cls.failure_class, has_token=bool(attempt.has_token), classification=cls)
    r.traces.append(Trace("outage delivery (nothing could be written; what the pipeline computed in memory)", [
        ("classify", f"{cls.failure_class.value} ({cls.source}): computed in memory, never written"),
        ("policy", f"{pol.action.value} in {human_delay(pol.delay_seconds)}: computed in memory, never written"),
        ("persist", f"decision commit REFUSED -> {error}"),
    ]))
    r.check(error is not None and error.startswith("event not acknowledged"), f"PipelineDBError raised: {error}")
    r.check(fx.calls == [] and fx.links() == [], "zero Razorpay calls, zero links during the outage")

    s3 = db.session()
    try:
        a = s3.get(PaymentAttempt, attempt_id)
        r.check(a is not None and _decisions(s3, attempt_id) == [] and _jobs(s3, attempt_id) == [],
                "after the outage the healthy database holds the ingested event and nothing else: no half-written decision or job")
        s = process_attempt(s3, a, execute_now=True, now=T0 + timedelta(minutes=5), rz_client=rz, llm_client=lm,
                            sleep=sleeps.append)
        r.traces.append(Trace("redelivery once the database is back", _trail(s3, attempt_id)))
        r.check(s["job_status"] == "sent" and s["duplicate"] is False and len(fx.links()) == 1,
                "redelivery: processed once, one link created, no skipped_duplicate (the outage delivery never reached the key)")
        crashed = _probe_crash_after_send(r, s3, fx, rz, lm, sleeps)
        lost = _probe_lost_response(r, s3, fx, lm, sleeps)
    finally:
        s3.close()

    r.fallback = ("PipelineDBError before any outbound call (event NOT acknowledged -> source redelivers); "
                  "after recovery the redelivery is processed once; a lost 'sent' write and a lost HTTP answer are "
                  "both resolved by reference_id lookup: the existing link is recorded, never re-created")
    r.final_state = ("outage delivery: PipelineDBError, 0 rows written, 0 Razorpay calls; "
                     f"redelivery: job#{s['job_id']} sent {s['link_url']}, links=1; "
                     f"crash-after-send probe: job#{crashed.id} sent {crashed.razorpay_link_url} (recovered by lookup); "
                     f"lost-response probe: job#{lost.id} sent {lost.razorpay_link_url} (reconciled, no follow-up); "
                     "still one link per payment")
    r.summary = "not acked, 0 calls; redelivery ok"


def _captured_payload(order_id: str, payment_id: str, amount: int, at: datetime) -> dict:
    """A payment.captured envelope for the ORIGINAL order (the shape docs/examples/payment_captured_webhook.json has)."""
    return {"entity": "event", "event": "payment.captured", "contains": ["payment"],
            "payload": {"payment": {"entity": {"id": payment_id, "entity": "payment", "amount": amount, "currency": "INR",
                                               "status": "captured", "captured": True, "order_id": order_id,
                                               "method": "upi", "created_at": to_unix(at)}}},
            "created_at": to_unix(at)}


class _CancelRefused:
    """Razorpay answers every cancel with a 502; creates, fetches and lookups pass through to the fixture."""
    name = "cancel-refused"

    def __init__(self, inner: FixtureRazorpayClient):
        self.inner, self.cancel_calls = inner, 0

    def create_payment_link(self, payload: dict) -> dict:
        return self.inner.create_payment_link(payload)

    def fetch_payment_link(self, link_id: str) -> dict:
        return self.inner.fetch_payment_link(link_id)

    def list_payment_links(self, *, reference_id: str) -> list[dict]:
        return self.inner.list_payment_links(reference_id=reference_id)

    def list_order_payments(self, order_id: str) -> list[dict]:
        return self.inner.list_order_payments(order_id)

    def cancel_payment_link(self, link_id: str) -> dict:
        self.cancel_calls += 1
        raise RazorpayError(502, "SERVER_ERROR", "Gateway is down")


def _cancels(fx: FixtureRazorpayClient) -> int:
    return sum(1 for name, _ in fx.calls if name == "cancel_payment_link")


def _order_checks(fx: FixtureRazorpayClient) -> int:
    return sum(1 for name, _ in fx.calls if name == "list_order_payments")


def scenario_order_paid_elsewhere(r: Result, session, sleeps: list) -> None:
    """Four steps. (1) The order is paid between the decision and the execution: the pending job is
    voided, run-due creates nothing, a stale payment.failed for the same order is refused at
    schedule. (2) The pre-send order check (CHECK_ORDER_BEFORE_SEND forced on) finds the payment
    the webhook has not reported yet. (3) The order is paid after the link went out: the link is
    cancelled, once. (4) Razorpay refuses the cancel: the job is parked for a person."""
    rz = razorpay_client.get_client()
    fx = razorpay_client.fixture()
    lm = llm.get_client()
    r.check(isinstance(rz, FixtureRazorpayClient), "no client fault: the fixture answers every create and cancel")

    # (1) paid between decision and execution
    ev = _event(FailureClass.INSUFFICIENT_FUNDS, 1)  # upi, no token: link in 48h, not executed at T0
    r.events.append(_describe_event(ev) + "  [scheduled at T0 for T0+48h; the order is paid at T0+30m; run-due at T0+48h]")
    s = _deliver(session, ev, now=T0, rz=rz, lm=lm, sleeps=sleeps, execute_now=False)
    r.check(s["job_status"] == "pending" and s["scheduled_at"] == T0 + timedelta(hours=48) and fx.calls == [],
            "delivery: job pending for T0+48h, nothing sent yet")
    paid1 = _captured_payload(ev["order_id"], "pay_ChaosElsewhere01", ev["amount_paise"], T0 + timedelta(minutes=30))
    out1 = ingest.ingest_event(session, paid1, now=T0 + timedelta(minutes=30), rz_client=rz, event_id="evt_chaos_captured_1")
    job = session.get(RecoveryJob, s["job_id"])
    a1 = session.get(PaymentAttempt, s["attempt_id"])
    o1 = _outcome(session, s["attempt_id"])
    r.check(out1["matched"] and out1["voided"] == [job.id] and out1["cancelled"] == [] and out1["parked"] == [],
            "payment.captured at T0+30m matched the attempt by order_id and voided the pending job")
    r.check(job.status == "no_action" and job.last_error == "order already paid by pay_ChaosElsewhere01",
            "job no_action with last_error 'order already paid by pay_ChaosElsewhere01'")
    r.check(a1.order_paid_at == T0 + timedelta(minutes=30) and a1.paid_by_payment_id == "pay_ChaosElsewhere01",
            "attempt row records order_paid_at (the capture time) and paid_by_payment_id")
    r.check(o1 is not None and o1.recovered is False and o1.amount_recovered_paise == 0 and o1.note == executor.ORDER_PAID_NOTE,
            f"outcome written: not recovered, amount 0, note '{executor.ORDER_PAID_NOTE}'")
    ran = scheduler.run_due(session, now=T0 + timedelta(hours=48), rz_client=rz, llm_client=lm, sleep=sleeps.append)
    forced = executor.execute_job(session, job, client=rz, now=T0 + timedelta(hours=48), sleep=sleeps.append)
    r.check(ran == [] and forced.status == "no_action" and _creates(fx) == 0 and fx.links() == [] and fx.calls == [],
            "run-due at T0+48h executes nothing; execute_job forced on the job is refused; ZERO create calls, ZERO links")
    r.traces.append(Trace("(1) paid between decision and execution", _trail(session, s["attempt_id"])))

    stale = dict(ev, razorpay_payment_id="pay_ChaosStaleFail01", failed_minutes_ago=200)
    r.events.append("stale payment.failed for the SAME order, delivered after the capture: " + _describe_event(stale))
    s_stale = _deliver(session, stale, now=T0 + timedelta(hours=1), rz=rz, lm=lm, sleeps=sleeps, execute_now=True)
    o_stale = _outcome(session, s_stale["attempt_id"])
    r.check(s_stale["job_status"] == "no_action" and "order already paid by pay_ChaosElsewhere01" in (s_stale["last_error"] or "")
            and o_stale is not None and o_stale.note == executor.ORDER_PAID_NOTE and fx.calls == [],
            "a stale payment.failed for the paid order is refused at schedule (no_action, outcome written), zero calls")
    r.traces.append(Trace("(1b) stale payment.failed for the paid order", _trail(session, s_stale["attempt_id"])))

    # (2) the pre-send order check, against the fixture's memory
    ev2 = _event(FailureClass.AUTH_ABANDONED, 1)
    r.events.append("order-check probe (CHECK_ORDER_BEFORE_SEND=1; the fixture remembers a captured payment the webhook "
                    "has not delivered yet): " + _describe_event(ev2) + "  [execute_now]")
    flag_before = config.CHECK_ORDER_BEFORE_SEND
    config.CHECK_ORDER_BEFORE_SEND = "1"
    try:
        fx.mark_order_paid(ev2["order_id"], "pay_ChaosElsewhere02", ev2["amount_paise"], now=T0)
        s2 = _deliver(session, ev2, now=T0, rz=rz, lm=lm, sleeps=sleeps, execute_now=True)
    finally:
        config.CHECK_ORDER_BEFORE_SEND = flag_before
    a2 = session.get(PaymentAttempt, s2["attempt_id"])
    o2 = _outcome(session, s2["attempt_id"])
    r.check(s2["job_status"] == "no_action" and "pay_ChaosElsewhere02" in (s2["last_error"] or "")
            and _order_checks(fx) == 1 and _creates(fx) == 0 and fx.links() == [],
            "order check: one GET /orders/{id}/payments, a captured payment found, no_action, zero creates, zero links")
    r.check(a2.paid_by_payment_id == "pay_ChaosElsewhere02" and o2 is not None and o2.note == executor.ORDER_PAID_NOTE,
            "the check's finding is recorded on the attempt and the outcome is written")
    r.traces.append(Trace("(2) order-check probe", _trail(session, s2["attempt_id"])))

    # (3) paid after the link was sent
    ev3 = _event(FailureClass.HARD_DECLINE, 0)  # delay 0: the link goes out at T0
    r.events.append(_describe_event(ev3) + "  [link sent at T0; the order is paid at T0+2h]")
    s3 = _deliver(session, ev3, now=T0, rz=rz, lm=lm, sleeps=sleeps, execute_now=False)
    r.check(s3["job_status"] == "sent" and len(fx.links()) == 1, "delivery: link created and sent at T0")
    paid3 = _captured_payload(ev3["order_id"], "pay_ChaosElsewhere03", ev3["amount_paise"], T0 + timedelta(hours=2))
    out3 = ingest.ingest_event(session, paid3, now=T0 + timedelta(hours=2), rz_client=rz, event_id="evt_chaos_captured_3")
    job3 = session.get(RecoveryJob, s3["job_id"])
    o3 = _outcome(session, s3["attempt_id"])
    link3 = fx.fetch_payment_link(job3.razorpay_link_id)
    r.check(out3["cancelled"] == [job3.id] and out3["voided"] == [] and out3["parked"] == [],
            "payment.captured at T0+2h: the live link's job is the one cancelled")
    r.check(_cancels(fx) == 1 and link3["status"] == "cancelled",
            "exactly one POST /payment_links/{id}/cancel; the link is 'cancelled' at the fixture")
    r.check(job3.status == "cancelled" and "order already paid by pay_ChaosElsewhere03" in (job3.last_error or ""),
            "job status cancelled, last_error names the paying payment")
    r.check(o3 is not None and o3.recovered is False and o3.amount_recovered_paise == 0
            and o3.note.startswith(executor.ORDER_PAID_NOTE) and job3.razorpay_link_id in o3.note,
            "outcome written: not recovered, amount 0, note says the link was cancelled")
    r.check(pipeline.open_link_jobs(session) == [] and pipeline.poll_outcomes(session, rz_client=rz, now=T0 + timedelta(hours=3)) == [],
            "the cancelled link is no longer open: poll has nothing to ask about")
    again = ingest.ingest_event(session, paid3, now=T0 + timedelta(hours=2, minutes=1), rz_client=rz, event_id="evt_chaos_captured_3")
    outcomes3 = session.execute(select(Outcome).where(Outcome.job_id == job3.id)).scalars().all()
    r.check(again["already_recorded"] is True and again["cancelled"] == [] and _cancels(fx) == 1 and len(outcomes3) == 1,
            "redelivered payment.captured: recorded as such, no second cancel call, no second outcome")
    r.traces.append(Trace("(3) paid after the link was sent", _trail(session, s3["attempt_id"])))

    # (4) the cancel is refused
    ev4 = _event(FailureClass.NETWORK_TIMEOUT, 1)  # upi, no token: link path
    r.events.append("cancel-refused probe (Razorpay answers 502 to the cancel): " + _describe_event(ev4) + "  [execute_now]")
    s4 = _deliver(session, ev4, now=T0, rz=rz, lm=lm, sleeps=sleeps, execute_now=True)
    refusing = _CancelRefused(fx)
    paid4 = _captured_payload(ev4["order_id"], "pay_ChaosElsewhere04", ev4["amount_paise"], T0 + timedelta(hours=1))
    out4 = ingest.ingest_event(session, paid4, now=T0 + timedelta(hours=1), rz_client=refusing, event_id="evt_chaos_captured_4")
    job4 = session.get(RecoveryJob, s4["job_id"])
    o4 = _outcome(session, s4["attempt_id"])
    link4 = fx.fetch_payment_link(job4.razorpay_link_id)
    r.check(s4["job_status"] == "sent" and out4["parked"] == [job4.id] and out4["cancelled"] == [] and refusing.cancel_calls == 1,
            "the cancel was attempted once and refused (502); the job is reported parked, not cancelled")
    r.check(job4.status == "human_queue" and "cancelling live link" in (job4.last_error or "") and "502" in (job4.last_error or ""),
            "job human_queue; last_error says the link is still live and why the cancel failed")
    r.check(o4 is not None and not o4.recovered and o4.note.startswith("human_queue") and "a person cancels" in o4.note,
            "outcome written: human_queue, a person cancels the link")
    r.check(link4["status"] == "created" and _cancels(fx) == 1,
            "the link really is still live at the fixture (only the earlier probe's cancel reached it): the trail says so, nothing is silent")
    r.traces.append(Trace("(4) cancel refused", _trail(session, s4["attempt_id"])))

    r.fallback = ("paid before execution: pending job voided (no_action + outcome), execute refuses, zero links; a stale "
                  "payment.failed for the order is refused at schedule; the pre-send order check catches an unreported "
                  "payment; paid after sending: one cancel call, job cancelled + outcome; cancel refused: human_queue with "
                  "the reason")
    r.final_state = (f"(1) job#{job.id} no_action, links=0, calls=0, outcome '{executor.ORDER_PAID_NOTE}'; "
                     f"(1b) stale job#{s_stale['job_id']} no_action at schedule; "
                     f"(2) job#{s2['job_id']} no_action after 1 order check, links=0; "
                     f"(3) job#{job3.id} cancelled, link {job3.razorpay_link_id} cancelled at Razorpay, 1 cancel call, outcome written; "
                     f"(4) job#{job4.id} human_queue (cancel 502), link {job4.razorpay_link_id} still live and flagged")
    r.summary = "0 links before; 1 cancel after"


SCENARIOS = {
    "llm_timeout": scenario_llm,
    "llm_bad_json": scenario_llm,
    "llm_hallucinated_class": scenario_llm,
    "razorpay_429": scenario_razorpay_429,
    "razorpay_5xx": scenario_razorpay_5xx,
    "duplicate_event": scenario_duplicate_event,
    "unknown_error_code": scenario_unknown_error_code,
    "db_unavailable": scenario_db_unavailable,
    "order_paid_elsewhere": scenario_order_paid_elsewhere,
}
assert set(SCENARIOS) == set(faults.FAULTS), "every fault in app/faults.py needs a scenario here"


# ---- runner ------------------------------------------------------------------------------------

def run_fault(name: str, workdir: Path) -> Result:
    """One fault on a fresh throwaway database, with the fixture reset and no keys. Restores the
    database binding, the keys and the fault registry afterwards, whatever happened."""
    r = Result(fault=name, inject=INJECT[name])
    url_before = db.url()
    keys_before = (config.RAZORPAY_KEY_ID, config.RAZORPAY_KEY_SECRET, config.ANTHROPIC_API_KEY)
    config.RAZORPAY_KEY_ID = config.RAZORPAY_KEY_SECRET = config.ANTHROPIC_API_KEY = ""
    faults.clear()
    razorpay_client.reset_fixture()
    path = workdir / f"{name}.db"
    for suffix in ("", "-journal"):
        Path(str(path) + suffix).unlink(missing_ok=True)
    db.configure(f"sqlite:///{path}")
    session = None
    try:
        db.init_db()
        faults.activate(name)
        session = db.session()
        SCENARIOS[name](r, session, [])
    except Exception as exc:  # one broken scenario must not hide the other eight
        r.error = f"{type(exc).__name__}: {exc}"
    finally:
        if session is not None:
            session.close()
        faults.clear()
        razorpay_client.reset_fixture()
        db.configure(url_before)
        config.RAZORPAY_KEY_ID, config.RAZORPAY_KEY_SECRET, config.ANTHROPIC_API_KEY = keys_before
    return r


def run_all(names, workdir: Path) -> list[Result]:
    return [run_fault(n, workdir) for n in names]


# ---- rendering ---------------------------------------------------------------------------------

def render_text(r: Result) -> str:
    lines = [f"FAULT {r.fault}", f"  inject      : {r.inject}"]
    lines += [f"  event       : {e}" for e in r.events]
    for t in r.traces:
        label = f"   [{t.label}]" if len(r.traces) > 1 else ""
        lines.append(f"  path        : {t.path()}{label}")
        lines += [f"      {stage:<9} {_clip(_relative(msg))}" for stage, msg in t.trail]
    lines.append(f"  fallback    : {r.fallback}")
    lines.append(f"  final state : {r.final_state}")
    lines += [f"  {'check ok   ' if ok else 'CHECK FAIL '}: {what}" for ok, what in r.checks]
    if r.error:
        lines.append(f"  error       : {r.error}")
    lines.append(f"  verdict     : {r.verdict}  {INVARIANT[r.fault]}")
    return "\n".join(lines)


def render_summary(results: list[Result]) -> str:
    headers = ["fault", "injected at", "fallback", "final state", "verdict"]
    rows = [[r.fault, INJECTED_AT[r.fault], _clip(r.fallback, 70), r.summary, r.verdict] for r in results]
    widths = [max(len(h), *(len(row[i]) for row in rows)) for i, h in enumerate(headers)]
    fmt = lambda cells: "  ".join(c.ljust(w) for c, w in zip(cells, widths)).rstrip()  # noqa: E731
    passed = sum(1 for r in results if r.passed)
    body = [fmt(headers), fmt(["-" * w for w in widths])] + [fmt(row) for row in rows]
    return "\n".join(["SUMMARY"] + body + [f"{len(results)} faults: {passed} PASS, {len(results) - passed} FAIL"])


def render_markdown(results: list[Result]) -> str:
    md = [
        "# Failure report",
        "",
        "Generated by `scripts/chaos.py --all --write docs/failure_report.md`; re-run with `make chaos`. "
        "Every fault in `app/faults.py` is injected at the client boundary where it would happen in production "
        "(the LLM client, the Razorpay client, the database engine, the event source), and a real event is run "
        "through the real pipeline. The run is deterministic and offline: a throwaway SQLite file per fault, the "
        "in-memory Razorpay fixture, no LLM key, a fixed clock (timestamps are offsets from T0) and injected "
        "sleeps (backoff waits are recorded, not slept). Nothing here touches the network, and the file is "
        "reproducible byte for byte.",
        "",
        "How to read a section: **inject** is what was broken; **path** is the stage sequence taken, from the "
        "audit rows the run actually wrote; **fallback** is the degrade the code chose; **final state** is what "
        "the database holds afterwards; **checks** are the invariants asserted, and the script exits non-zero if "
        "any of them fails.",
        "",
        "## Summary",
        "",
        "| # | fault | injected at | fallback | final state | verdict |",
        "|---|---|---|---|---|---|",
    ]
    for i, r in enumerate(results, 1):
        md.append(f"| {i} | `{r.fault}` | {INJECTED_AT[r.fault]} | {r.fallback} | {r.summary} | **{r.verdict}** |")
    passed = sum(1 for r in results if r.passed)
    md += ["", f"{len(results)} faults: {passed} PASS, {len(results) - passed} FAIL.", ""]

    for i, r in enumerate(results, 1):
        md += [f"## {i}. {r.fault}", "", f"**Inject:** {r.inject}", ""]
        md += [f"**Event:** {e}  " for e in r.events]
        md.append("")
        for t in r.traces:
            label = f" ({t.label})" if len(r.traces) > 1 else ""
            md += [f"**Path{label}:** `{t.path()}`", "", "```text"]
            md += [f"{stage:<9} {_clip(_relative(msg))}" for stage, msg in t.trail]
            md += ["```", ""]
        md += [f"**Fallback:** {r.fallback}", "", f"**Final state:** {r.final_state}", "", "**Checks:**"]
        md += [f"- {'ok' if ok else 'FAIL'}: {what}" for ok, what in r.checks]
        if r.error:
            md.append(f"- error: {r.error}")
        md += ["", f"**Verdict:** {r.verdict} ({INVARIANT[r.fault]})", "",
               f"**Why this is the right degrade for a money path:** {WHY[r.fault]}", ""]

    md += [
        "## What this report does not cover",
        "",
        "- The live HTTP paths (`LiveRazorpayClient`, `AnthropicLLM`) are not exercised: the faults are injected "
        "one layer below them, on the same interfaces they implement, so the pipeline's handling is what is tested, "
        "not the wire format of a real 429 or a real API timeout.",
        "- Two processes executing the same pending job at the same instant are not simulated; the single-process "
        "scheduler makes that impossible here, and the Razorpay `reference_id` guard shown under `db_unavailable` "
        "is what would catch it.",
        "- The `reference_id` uniqueness at Razorpay, the lookup by `reference_id` (`GET /payment_links?"
        "reference_id=`) that the reconcile step and the crash probes rely on, the shape of "
        "`POST /payment_links/{id}/cancel` and of `GET /orders/{id}/payments` that `order_paid_elsewhere` relies on, "
        "are assumptions stated in `FixtureRazorpayClient`. If the real API accepted duplicates, the worst case in the crash-after-send probe "
        "would be a redundant link, never a second charge, because a Payment Link only collects money when a "
        "customer chooses to pay it; if the lookup answered differently, the reconcile step reports `unknown` and "
        "parks the payment for a person instead of minting a follow-up.",
        "",
    ]
    return "\n".join(md)


# ---- entrypoint -------------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="python scripts/chaos.py", description=__doc__.split("\n\n")[0])
    g = p.add_mutually_exclusive_group(required=True)
    g.add_argument("--fault", choices=faults.FAULTS, help="inject one fault")
    g.add_argument("--all", action="store_true", help="inject every fault in turn and print a summary")
    p.add_argument("--write", metavar="PATH", help="with --all: also write the report as Markdown to PATH")
    args = p.parse_args(argv)
    if args.write and not args.all:
        p.error("--write needs --all: the report covers every fault or none")

    names = list(faults.FAULTS) if args.all else [args.fault]
    workdir = Path(tempfile.mkdtemp(prefix="pra-chaos-"))
    print("payment-recovery-agent chaos harness")
    print(f"  faults   : {', '.join(names)}")
    print(f"  database : throwaway SQLite per fault under {workdir} (never ./recovery.db)")
    print("  razorpay : in-memory fixture (RAZORPAY_KEY_ID forced empty for this run); razorpay_* faults wrap it")
    print("  llm      : none (ANTHROPIC_API_KEY forced empty for this run); llm_* faults inject FaultingLLM")
    print("  clock    : fixed T0; timestamps print as offsets; backoff sleeps are recorded, not waited")
    try:
        results = []
        for name in names:
            r = run_fault(name, workdir)
            results.append(r)
            print()
            print(render_text(r))
        if args.all:
            print()
            print(render_summary(results))
        if args.write:
            out = Path(args.write)
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(render_markdown(results), encoding="utf-8")
            print(f"wrote {out}")
    finally:
        shutil.rmtree(workdir, ignore_errors=True)
    return 0 if all(r.passed for r in results) else 1


if __name__ == "__main__":
    sys.exit(main())
